config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  #
  resources :restaurants do
    # member do
    #   resources :reviews
    # end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  categories = %w[chinese italian japanese french belgian]

  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: categories }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, :rating, presence: true
  validates :rating, numericality: { only_integer: true }, inclusion: { in: (0..5) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new

  end

  def create

  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<div class="container">

  <div class="d-flex justify-content-between align-items-center">
    <p>Logo</p>
    <h1>Restaurants</h1>
    <%= link_to "Add Restaurant", new_restaurant_path, class: "btn btn-primary" %>
  </div>



  <div class="row justify-content-center">
    <% @restaurants.each do |restaurant| %>
    <div class="col-3 m-3">
      <div class="card" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title"><%= restaurant.name %></h5>
          <h6 class="card-subtitle mb-2 text-muted"><%= restaurant.category %></h6>
          <p class="card-text"><%= restaurant.address %></p>
          <%= link_to "See restaurant", restaurant %>
          <%# <a href="#" class="card-link">Card link</a>
          <a href="#" class="card-link">Another link</a> %>
        </div>
      </div>
    </div>
    <% end %>
  </div>



</div>

app/views/restaurants/show.html.erb
<%= @restaurant.name %>